services:
  - type: web
    name: personal-assistant-chat
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
